#pragma config(Sensor, S3,     Colour,         sensorEV3_Color, modeEV3Color_Reflected)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//




task main()
{


int countline = 0;

while (true)
	{
displayCenteredBigTextLine(4,"Line detect : %d",countline);

	if (SensorValue[Colour] <=36)
		{
			sleep(500);
			countline = countline + 1;
		}

	else {

		setMotorSync(motorB,motorC,0,10);
		}
	}







}
